= Deployment Strategies with Argo CD and Argo Rollouts
include::_attributes.adoc[]

TODO 

## Introduction
### Microservices architecture

The traditional approach to building applications has focused on the monolith - having all deployable parts of the app contained within that single app. *Microservice Architectures* help solve these issues and boost development and response. It's one of the main factors of a *Cloud Native development*. Now, we have several applications that have dependencies on each other and also have other dependencies like brokers or databases.

Applications have their own life cycle, so we should be able to execute independent deployments. All the applications and dependencies will not change their version at the same time. Therefore, microservices enable your development team to roll out software solutions more quickly and better react to customer needs.

### Continuous delivery

Another important topic in Cloud Native practices is *Continuous Delivery*. Continuous delivery, often abbreviated as CD, is a set of practices in which *code changes are automatically deployed into an acceptance environment*. CD crucially includes procedures to ensure that software is adequately tested before deployment and provides a way to roll back changes if deemed necessary.

### Progressive Delivery

Progressive delivery is the process of releasing updates of a product in a controlled and gradual manner, thereby reducing the risk of the release, typically coupling automation and metric analysis to drive the automated promotion or rollback of the update.

Progressive delivery is often described as an evolution of continuous delivery, extending the speed benefits made in CI/CD to the deployment process. This is accomplished by limiting the exposure of the new version to a subset of users, observing and analyzing for correct behavior, then progressively increasing the exposure to a broader and wider audience while continuously verifying correctness.


### Argo Rollouts
https://argoproj.github.io/argo-rollouts/[Argo Rollouts] is a Kubernetes controller and set of CRDs which provide advanced deployment capabilities such as blue-green, canary, canary analysis, experimentation, and progressive delivery features to Kubernetes.
TODO improve this

## Deployment Strategies

TODO Briefly explain the 3 scenarios
Blue/Green Deployment
Canary Deployment
(optional)Canary Deployment with Service Mesh
## Explain the application that we are going to use for the 3 scenarios
TODO with helm umbrella is already done


